In [1]:
import pandas as pd

In [4]:
ser = pd.Series([10,20,40,77,99,80])
print(ser)

0    10
1    20
2    40
3    77
4    99
5    80
dtype: int64

In [6]:
# Customised index
ser = pd.Series([10,20,40,77,99,80],index = ['a','b','c','d','e','f'])
print(ser)

a    10
b    20
c    40
d    77
e    99
f    80
dtype: int64

In [7]:
# Recomended to use the default index but if need create a index using the string

In [8]:
print(ser.size)
print(ser.shape)
print(ser.dtype)

6
(6,)
int64

In [9]:
# Create a pandas series with index
ser = pd.Series([10,20,40,77,99,80],index = ['a','b','c','d','e','f'])
print(ser)

a    10
b    20
c    40
d    77
e    99
f    80
dtype: int64

In [14]:
# Create a series of marks.check the type , size and shape
marks = pd.Series([100,40,79,80,45],index=['1','2','3','4','5'])
print(marks)
print(marks.size)
print(marks.shape)
print(marks.dtype)

1    100
2     40
3     79
4     80
5     45
dtype: int64
5
(5,)
int64

# Dictionary to series

In [15]:
ser = pd.Series({'a':1,'b':2,'c':3,'d':4})
ser

a    1
b    2
c    3
d    4
dtype: int64

# key - index
# values - series values

In [17]:
# Create a dictionary convert to a pandas series.print the index and values
stu = pd.Series({'tharshi':21,'thannu':23,'Pavu':24})
print(stu)

tharshi    21
thannu     23
Pavu       24
dtype: int64

In [18]:
ser.to_frame()

   0
a  1
b  2
c  3
d  4

# Indexing and Slicing

In [24]:
ser = pd.Series([23.2,42,8,56.7,44.3])
ser.to_frame()

      0
0  23.2
1  42.0
2   8.0
3  56.7
4  44.3

In [22]:
ser[0]

np.float64(23.2)

In [25]:
ser[0:4]

0    23.2
1    42.0
2     8.0
3    56.7
dtype: float64

In [26]:
ser[0:4:2]

0    23.2
2     8.0
dtype: float64

In [34]:
ser = pd.Series([23.2, 42, 8, 56.7, 44.3],index=['a', 'b', 'c', 'd', 'e'])

print(ser)

a    23.2
b    42.0
c     8.0
d    56.7
e    44.3
dtype: float64

In [35]:
ser["a"]

np.float64(23.2)

In [36]:
ser["d"]

np.float64(56.7)

In [37]:
ser["a":"c"]

a    23.2
b    42.0
c     8.0
dtype: float64

In [48]:
d = {'hi' : 2,'hello' :4 ,'how' :3,'are' : 3,'you' : 3}
ser = pd.Series(d)
print(ser)
print(d[0:1])

ser = pd.Series([23.2, 42, 8, 56.7, 44.3],index=['a', 'b', 'c', 'd', 'e'])

print(ser)

hi       2
hello    4
how      3
are      3
you      3
dtype: int64

TypeError: unhashable type: 'slice'

In [57]:
ser = pd.Series(["one",'two','three','four'])
ser

0      one
1      two
2    three
3     four
dtype: object

In [58]:
ser [4] = "five"
ser

0      one
1      two
2    three
3     four
4     five
dtype: object

# Deleting Elements
**Syntax**:- ser_name.drop(index = [index of values needs to be dropped])

In [61]:
ser.drop(index=[3])

0      one
1      two
2    three
4     five
dtype: object

In [64]:
ser[2] ="hundered"
ser

0         one
1         two
2    hundered
3        four
4        five
dtype: object

In [69]:
ser.drop(ser.index[[1, 4]], inplace=True)
print(ser)

0         one
2    hundered
3        four
dtype: object

In [70]:
ser.reset_index(drop=True)

0         one
1    hundered
2        four
dtype: object

In [72]:
ser.reset_index(drop = True, inplace = True)
ser

0         one
1    hundered
2        four
dtype: object

# Data Frames

In [1]:
#key = col_names
# list of values = elements of each column
# Syntax:- 
# Data_frame

In [3]:
import pandas as pd
emp_data = pd.DataFrame({"emp_id":[101,102,103,104,105],
                        "name":['tharshi','thannu','pavi','Taj','priya'],
                        "dept":["AIML","ML","DS","DA","Pd"],
                        "salary":[20,30,40,58,69]})
emp_data

   emp_id     name  dept  salary
0     101  tharshi  AIML      20
1     102   thannu    ML      30
2     103     pavi    DS      40
3     104      Taj    DA      58
4     105    priya    Pd      69

In [11]:
emp_id=pd.Series([101,102,103,104,105])
emp_name = pd.Series(['tharshi','thannu','pavi','Taj','priya'])
dept = pd.Series(["AIML","ML","DS","DA","Pd"])
salary = pd.Series([20,30,40,58,69])

emp_data = pd.DataFrame([emp_id,emp_name,dept,salary],index = ['emp_id','emp_name','dept','salary']).T

In [12]:
emp_data

  emp_id emp_name  dept salary
0    101  tharshi  AIML     20
1    102   thannu    ML     30
2    103     pavi    DS     40
3    104      Taj    DA     58
4    105    priya    Pd     69

In [ ]:
# creating

In [14]:
emp_id=[101,102,103,104,105]
emp_name = ['tharshi','thannu','pavi','Taj','priya']
dept = ["AIML","ML","DS","DA","Pd"]
salary = [20,30,40,58,69]

emp_data = pd.DataFrame({"id":emp_id,"name":emp_name,"Dept":dept,"Salary":salary})

In [15]:
emp_data

    id     name  Dept  Salary
0  101  tharshi  AIML      20
1  102   thannu    ML      30
2  103     pavi    DS      40
3  104      Taj    DA      58
4  105    priya    Pd      69

In [17]:
pd.DataFrame([[101,"tharshi","AIML",20],
              [102,"thannu",'ML',30],
              [103,'pavi','DS',40],
              [104,'Taj','DA',58],
              [105,'priya','Pd',69]],columns = ["emp_id","name","dept","salary"])

   emp_id     name  dept  salary
0     101  tharshi  AIML      20
1     102   thannu    ML      30
2     103     pavi    DS      40
3     104      Taj    DA      58
4     105    priya    Pd      69

In [19]:
names = ['Ram', 'John', 'Abdul','Siva', 'Adam', 'Rahman']
maths =  [45, 40, 60, 80, 90, 75]
english =[60,75,90,65,80,60]
stu_data = pd.DataFrame({"stu_names":names,"Maths_marks":maths,'English_marks':english})
stu_data

  stu_names  Maths_marks  English_marks
0       Ram           45             60
1      John           40             75
2     Abdul           60             90
3      Siva           80             65
4      Adam           90             80
5    Rahman           75             60

In [41]:
scores_df = pd.DataFrame([['Ram',45,60],
                           ['John',40,75],
                           ['Abdul',60,90],
                           ['Siva',80,65],
                           ['Adam',90,80],
                          ['Rahman',75,60]],columns = ["names","maths","english"])
scores_df

    names  maths  english
0     Ram     45       60
1    John     40       75
2   Abdul     60       90
3    Siva     80       65
4    Adam     90       80
5  Rahman     75       60

In [47]:
scores_df = pd.DataFrame([['Ram',45,60],
                           ['John',40,75],
                           ['Abdul',60,90],
                           ['Siva',80,65],
                           ['Adam',90,80],
                          ['Rahman',75,60]],columns = ["names","maths","english"]).T
scores_df

           0     1      2     3     4       5
names    Ram  John  Abdul  Siva  Adam  Rahman
maths     45    40     60    80    90      75
english   60    75     90    65    80      60

In [42]:
scores_df.head(3)

   names  maths  english
0    Ram     45       60
1   John     40       75
2  Abdul     60       90

In [43]:
scores_df.head() #default it will take the frist 5 rows

   names  maths  english
0    Ram     45       60
1   John     40       75
2  Abdul     60       90
3   Siva     80       65
4   Adam     90       80

In [44]:
scores_df.tail(2)

    names  maths  english
4    Adam     90       80
5  Rahman     75       60

In [45]:
scores_df.tail(4)

    names  maths  english
2   Abdul     60       90
3    Siva     80       65
4    Adam     90       80
5  Rahman     75       60

In [46]:
scores_df.tail() # default it will take the bottom 5

    names  maths  english
1    John     40       75
2   Abdul     60       90
3    Siva     80       65
4    Adam     90       80
5  Rahman     75       60

In [52]:
score_df = pd.DataFrame([['A',70,8],
                           ['B',80,8],
                           ['C',90,9],
                           ['D',100,9],
                           ['E',100,10],
                          ['F',70,10]],columns = ["student_name","marks","class"])
score_df

  student_name  marks  class
0            A     70      8
1            B     80      8
2            C     90      9
3            D    100      9
4            E    100     10
5            F     70     10

In [53]:
score_df.head(3)

  student_name  marks  class
0            A     70      8
1            B     80      8
2            C     90      9

In [54]:
score_df.tail(3)

  student_name  marks  class
3            D    100      9
4            E    100     10
5            F     70     10

#  Data Frame Indexing and Slicing

**iloc** - index location

**Synatax**:- df_name.iloc[row_index,col_index]

In [59]:
score_df.iloc[[0,3,5],[1]]

   marks
0     70
3    100
5     70

In [60]:
score_df.iloc[[0,3,5],[1,2]]

   marks  class
0     70      8
3    100      9
5     70     10

# slicing

In [62]:
score_df.iloc[2:,0:3:1]

  student_name  marks  class
2            C     90      9
3            D    100      9
4            E    100     10
5            F     70     10

In [67]:
score_df.iloc[2:5:1,0:3:1]

  student_name  marks  class
2            C     90      9
3            D    100      9
4            E    100     10

In [76]:
score_df.iloc[::2,1::]

   marks  class
0     70      8
2     90      9
4    100     10

In [70]:
score_df.iloc[::2,:]

  student_name  marks  class
0            A     70      8
2            C     90      9
4            E    100     10

In [71]:
score_df.iloc[:,::2]

  student_name  class
0            A      8
1            B      8
2            C      9
3            D      9
4            E     10
5            F     10

In [77]:
names = ['Ram', 'John', 'Abdul','Siva', 'Adam', 'Rahman']
maths =  [45, 40, 60, 80, 90, 75]
english =[60,75,90,65,80,60]
di = {"stu_names":names,"Maths_marks":maths,'English_marks':english}
s_df=pd.DataFrame(di)
s_df

  stu_names  Maths_marks  English_marks
0       Ram           45             60
1      John           40             75
2     Abdul           60             90
3      Siva           80             65
4      Adam           90             80
5    Rahman           75             60

In [89]:
# index 1 rows and maths using iloc
s_df.iloc[[0],[1]]

   Maths_marks
0           45

In [90]:
# index 1,2,3 and maths mark using iloc
s_df.iloc[[1,2,3],[1]]

   Maths_marks
1           40
2           60
3           80

In [92]:
# index 1,2,3 and english mark using iloc
s_df.iloc[[1,3,4],[2]]

   English_marks
1             75
3             65
4             80

# loc - name based indexing

In [94]:
s_df.loc[0,"stu_names"]

'Ram'

In [97]:
s_df.loc[[0,1,4],["stu_names","Maths_marks","English_marks"]]

  stu_names  Maths_marks  English_marks
0       Ram           45             60
1      John           40             75
4      Adam           90             80

# slicing

In [100]:
s_df.loc[0:4:1, "stu_names":"Maths_marks"]

  stu_names  Maths_marks
0       Ram           45
1      John           40
2     Abdul           60
3      Siva           80
4      Adam           90

# Mixing of indexing and slicing

In [101]:
s_df.loc[0:4:1, ["stu_names","Maths_marks"]]

  stu_names  Maths_marks
0       Ram           45
1      John           40
2     Abdul           60
3      Siva           80
4      Adam           90

In [102]:
s_df["stu_names"]

0       Ram
1      John
2     Abdul
3      Siva
4      Adam
5    Rahman
Name: stu_names, dtype: object

In [104]:
s_df[["stu_names", "Maths_marks"]]

  stu_names  Maths_marks
0       Ram           45
1      John           40
2     Abdul           60
3      Siva           80
4      Adam           90
5    Rahman           75

In [111]:
s_df.loc[[1],["Maths_marks"]]

   Maths_marks
1           40

In [114]:
s_df.loc[1:4,["Maths_marks"]]

   Maths_marks
1           40
2           60
3           80
4           90

In [108]:
s_df.loc[[1,3,4],["Maths_marks","English_marks"]]

   Maths_marks  English_marks
1           40             75
3           80             65
4           90             80

In [112]:
s_df[["Maths_marks"]]

   Maths_marks
0           45
1           40
2           60
3           80
4           90
5           75