# 📊 Pandas Task 2 – Student Performance Analysis

Give them this small dataset:

In [2]:
import pandas as pd

data = {
    "Name": ["Anu", "Ravi", "Priya", "Kiran", "Sneha", "Arjun", "Divya", "Rohit", "Meena", "Varun"],
    "Gender": ["F", "M", "F", "M", "F", "M", "F", "M", "F", "M"],
    "Department": ["Data Science", "Data Science", "Python", "Python", "Data Science",
                    "AI", "AI", "Python", "AI", "Data Science"],
    "Age": [22, 24, 21, 23, 25, 24, 22, 26, 23, 25],
    "Python": [85, 72, 95, 68, 89, 76, 92, 81, 88, 65],
    "SQL": [78, 88, 82, 74, 91, 69, 87, 79, 93, 72],
    "Pandas": [90, 75, 91, 70, 86, 80, 95, 73, 89, 68],
    "Attendance": [92, 85, 96, 78, 94, 82, 98, 88, 91, 75]
}

df = pd.DataFrame(data)

In [3]:
df

    Name Gender    Department  Age  Python  SQL  Pandas  Attendance
0    Anu      F  Data Science   22      85   78      90          92
1   Ravi      M  Data Science   24      72   88      75          85
2  Priya      F        Python   21      95   82      91          96
3  Kiran      M        Python   23      68   74      70          78
4  Sneha      F  Data Science   25      89   91      86          94
5  Arjun      M            AI   24      76   69      80          82
6  Divya      F            AI   22      92   87      95          98
7  Rohit      M        Python   26      81   79      73          88
8  Meena      F            AI   23      88   93      89          91
9  Varun      M  Data Science   25      65   72      68          75

# 🟢 Level 1 – DataFrame Basics

Create a Pandas DataFrame using the given data.

Display the first 5 records.

Display the last 3 records.

Find the number of rows and columns.

Display all column names.

Check the datatype of each column.

Display only the Name, Department, and Pandas columns.

Display the details of the student Priya.

Display the Python column.

Find the total number of students.

In [4]:
df.head(5)

    Name Gender    Department  Age  Python  SQL  Pandas  Attendance
0    Anu      F  Data Science   22      85   78      90          92
1   Ravi      M  Data Science   24      72   88      75          85
2  Priya      F        Python   21      95   82      91          96
3  Kiran      M        Python   23      68   74      70          78
4  Sneha      F  Data Science   25      89   91      86          94

In [5]:
df.tail(3)

    Name Gender    Department  Age  Python  SQL  Pandas  Attendance
7  Rohit      M        Python   26      81   79      73          88
8  Meena      F            AI   23      88   93      89          91
9  Varun      M  Data Science   25      65   72      68          75

In [6]:
df.shape

(10, 8)

In [8]:
print(df.columns)

Index(['Name', 'Gender', 'Department', 'Age', 'Python', 'SQL', 'Pandas',
       'Attendance'],
      dtype='object')

In [9]:
df.dtypes

Name          object
Gender        object
Department    object
Age            int64
Python         int64
SQL            int64
Pandas         int64
Attendance     int64
dtype: object

In [10]:
df[['Name','Department','Pandas']]

    Name    Department  Pandas
0    Anu  Data Science      90
1   Ravi  Data Science      75
2  Priya        Python      91
3  Kiran        Python      70
4  Sneha  Data Science      86
5  Arjun            AI      80
6  Divya            AI      95
7  Rohit        Python      73
8  Meena            AI      89
9  Varun  Data Science      68

In [11]:
df[df['Name']=="Priya"]

    Name Gender Department  Age  Python  SQL  Pandas  Attendance
2  Priya      F     Python   21      95   82      91          96

In [15]:
df[['Python']]

   Python
0      85
1      72
2      95
3      68
4      89
5      76
6      92
7      81
8      88
9      65

In [17]:
df.shape[0]

10

# 🟡 Level 2 – Filtering

Display students whose Python score is greater than 80.
    
Find students whose SQL score is less than 75.
    
Display students who scored more than 85 in Pandas.
    
Find students whose attendance is greater than 90%.
    
Display all female students.
    
Display all students from the AI department.
    
Find students who scored more than 80 in both Python and SQL.
    
Find students whose attendance is below 80%.
    
Display students from either AI or Data Science.
    
Find students whose Python score is between 70 and 90.

In [21]:
df[df["Python"]>80]

    Name Gender    Department  Age  Python  SQL  Pandas  Attendance
0    Anu      F  Data Science   22      85   78      90          92
2  Priya      F        Python   21      95   82      91          96
4  Sneha      F  Data Science   25      89   91      86          94
6  Divya      F            AI   22      92   87      95          98
7  Rohit      M        Python   26      81   79      73          88
8  Meena      F            AI   23      88   93      89          91

In [20]:
df[df["SQL"]<75]

    Name Gender    Department  Age  Python  SQL  Pandas  Attendance
3  Kiran      M        Python   23      68   74      70          78
5  Arjun      M            AI   24      76   69      80          82
9  Varun      M  Data Science   25      65   72      68          75

In [22]:
df[df["Attendance"]>90]

    Name Gender    Department  Age  Python  SQL  Pandas  Attendance
0    Anu      F  Data Science   22      85   78      90          92
2  Priya      F        Python   21      95   82      91          96
4  Sneha      F  Data Science   25      89   91      86          94
6  Divya      F            AI   22      92   87      95          98
8  Meena      F            AI   23      88   93      89          91

In [24]:
df[df["Gender"]=='F']

    Name Gender    Department  Age  Python  SQL  Pandas  Attendance
0    Anu      F  Data Science   22      85   78      90          92
2  Priya      F        Python   21      95   82      91          96
4  Sneha      F  Data Science   25      89   91      86          94
6  Divya      F            AI   22      92   87      95          98
8  Meena      F            AI   23      88   93      89          91

In [25]:
df[df["Department"]=='AI']

    Name Gender Department  Age  Python  SQL  Pandas  Attendance
5  Arjun      M         AI   24      76   69      80          82
6  Divya      F         AI   22      92   87      95          98
8  Meena      F         AI   23      88   93      89          91

In [26]:
df[(df['Python']>80) &(df['SQL']>80)]

    Name Gender    Department  Age  Python  SQL  Pandas  Attendance
2  Priya      F        Python   21      95   82      91          96
4  Sneha      F  Data Science   25      89   91      86          94
6  Divya      F            AI   22      92   87      95          98
8  Meena      F            AI   23      88   93      89          91

In [27]:
df[df["Attendance"]<80]

    Name Gender    Department  Age  Python  SQL  Pandas  Attendance
3  Kiran      M        Python   23      68   74      70          78
9  Varun      M  Data Science   25      65   72      68          75

In [30]:
df[(df["Department"] == "AI") | (df["Department"] == "Data Science")]

    Name Gender    Department  Age  Python  SQL  Pandas  Attendance
0    Anu      F  Data Science   22      85   78      90          92
1   Ravi      M  Data Science   24      72   88      75          85
4  Sneha      F  Data Science   25      89   91      86          94
5  Arjun      M            AI   24      76   69      80          82
6  Divya      F            AI   22      92   87      95          98
8  Meena      F            AI   23      88   93      89          91
9  Varun      M  Data Science   25      65   72      68          75

In [40]:
df[(df["Python"] > 70) & (df["Python"] < 90)].sort_values("Python")

    Name Gender    Department  Age  Python  SQL  Pandas  Attendance
1   Ravi      M  Data Science   24      72   88      75          85
5  Arjun      M            AI   24      76   69      80          82
7  Rohit      M        Python   26      81   79      73          88
0    Anu      F  Data Science   22      85   78      90          92
8  Meena      F            AI   23      88   93      89          91
4  Sneha      F  Data Science   25      89   91      86          94

# 🟠 Level 3 – New Columns & Calculations

Create a new column called Total containing the total marks of Python, SQL, and Pandas.
    
Create an Average column.
    
Find the student with the highest average.
    
Find the student with the lowest average.
    
Create a Result column:
    
Average >= 40 → "Pass"
    
Average < 40 → "Fail"
    
Create a Performance column:
    
Average >= 85 → "Excellent"
    
Average >= 75 → "Good"
    
Average >= 60 → "Average"
    
Otherwise → "Needs Improvement"
    
Create a column Attendance_Status:
    
Attendance >= 75 → "Eligible"
    
Attendance < 75 → "Not Eligible"

In [43]:
df["Total"] = df['Python']+df['SQL']+df['Pandas']
df

    Name Gender    Department  Age  Python  SQL  Pandas  Attendance  Total
0    Anu      F  Data Science   22      85   78      90          92    253
1   Ravi      M  Data Science   24      72   88      75          85    235
2  Priya      F        Python   21      95   82      91          96    268
3  Kiran      M        Python   23      68   74      70          78    212
4  Sneha      F  Data Science   25      89   91      86          94    266
5  Arjun      M            AI   24      76   69      80          82    225
6  Divya      F            AI   22      92   87      95          98    274
7  Rohit      M        Python   26      81   79      73          88    233
8  Meena      F            AI   23      88   93      89          91    270
9  Varun      M  Data Science   25      65   72      68          75    205

In [60]:
df['Average'] = df["Total"]/3
df

,Name,Gender,Department,Age,Python,SQL,Pandas,Attendance,Total,Average,Result,Performance
0,Anu,F,Data Science,22,85,78,90,92,253,84.333333,Fail,Needs Improvement
1,Ravi,M,Data Science,24,72,88,75,85,235,78.333333,Fail,Needs Improvement
2,Priya,F,Python,21,95,82,91,96,268,89.333333,Fail,Needs Improvement
3,Kiran,M,Python,23,68,74,70,78,212,70.666667,Fail,Needs Improvement
4,Sneha,F,Data Science,25,89,91,86,94,266,88.666667,Fail,Needs Improvement
5,Arjun,M,AI,24,76,69,80,82,225,75.000000,Fail,Needs Improvement
6,Divya,F,AI,22,92,87,95,98,274,91.333333,Fail,Needs Improvement
7,Rohit,M,Python,26,81,79,73,88,233,77.666667,Fail,Needs Improvement
8,Meena,F,AI,23,88,93,89,91,270,90.000000,Fail,Needs Improvement
9,Varun,M,Data Science,25,65,72,68,75,205,68.333333,Fail,Needs Improvement

In [61]:
df.loc[df[['Average']].idxmax()]

,Name,Gender,Department,Age,Python,SQL,Pandas,Attendance,Total,Average,Result,Performance
6,Divya,F,AI,22,92,87,95,98,274,91.333333,Fail,Needs Improvement

In [62]:
df.loc[df[['Average']].idxmin()]

,Name,Gender,Department,Age,Python,SQL,Pandas,Attendance,Total,Average,Result,Performance
9,Varun,M,Data Science,25,65,72,68,75,205,68.333333,Fail,Needs Improvement

In [63]:
df["Result"] = "Fail"

df.loc[df["Average"] >= 40, "Result"] = "Pass"

df

,Name,Gender,Department,Age,Python,SQL,Pandas,Attendance,Total,Average,Result,Performance
0,Anu,F,Data Science,22,85,78,90,92,253,84.333333,Pass,Needs Improvement
1,Ravi,M,Data Science,24,72,88,75,85,235,78.333333,Pass,Needs Improvement
2,Priya,F,Python,21,95,82,91,96,268,89.333333,Pass,Needs Improvement
3,Kiran,M,Python,23,68,74,70,78,212,70.666667,Pass,Needs Improvement
4,Sneha,F,Data Science,25,89,91,86,94,266,88.666667,Pass,Needs Improvement
5,Arjun,M,AI,24,76,69,80,82,225,75.000000,Pass,Needs Improvement
6,Divya,F,AI,22,92,87,95,98,274,91.333333,Pass,Needs Improvement
7,Rohit,M,Python,26,81,79,73,88,233,77.666667,Pass,Needs Improvement
8,Meena,F,AI,23,88,93,89,91,270,90.000000,Pass,Needs Improvement
9,Varun,M,Data Science,25,65,72,68,75,205,68.333333,Pass,Needs Improvement

In [64]:
df["Performance"] = "Needs Improvement"

df.loc[df["Average"] >= 60, "Performance"] = "Average"
df.loc[df["Average"] >= 75, "Performance"] = "Good"
df.loc[df["Average"] >= 85, "Performance"] = "Excellent"

df

,Name,Gender,Department,Age,Python,SQL,Pandas,Attendance,Total,Average,Result,Performance
0,Anu,F,Data Science,22,85,78,90,92,253,84.333333,Pass,Good
1,Ravi,M,Data Science,24,72,88,75,85,235,78.333333,Pass,Good
2,Priya,F,Python,21,95,82,91,96,268,89.333333,Pass,Excellent
3,Kiran,M,Python,23,68,74,70,78,212,70.666667,Pass,Average
4,Sneha,F,Data Science,25,89,91,86,94,266,88.666667,Pass,Excellent
5,Arjun,M,AI,24,76,69,80,82,225,75.000000,Pass,Good
6,Divya,F,AI,22,92,87,95,98,274,91.333333,Pass,Excellent
7,Rohit,M,Python,26,81,79,73,88,233,77.666667,Pass,Good
8,Meena,F,AI,23,88,93,89,91,270,90.000000,Pass,Excellent
9,Varun,M,Data Science,25,65,72,68,75,205,68.333333,Pass,Average

In [69]:
df["Attendance_Status"] = "Not Eligible"

df.loc[df["Attendance"] >= 75, "Attendance_Status"] = "Eligible"

df

,Name,Gender,Department,Age,Python,SQL,Pandas,Attendance,Total,Average,Result,Performance,Attendance_status,Not Eligible,Attendance_stattus,Attendance_Status
0,Anu,F,Data Science,22,85,78,90,92,253,84.333333,Pass,Good,,Eligible,Eligible,Eligible
1,Ravi,M,Data Science,24,72,88,75,85,235,78.333333,Pass,Good,,Eligible,Eligible,Eligible
2,Priya,F,Python,21,95,82,91,96,268,89.333333,Pass,Excellent,,Eligible,Eligible,Eligible
3,Kiran,M,Python,23,68,74,70,78,212,70.666667,Pass,Average,,Eligible,Eligible,Eligible
4,Sneha,F,Data Science,25,89,91,86,94,266,88.666667,Pass,Excellent,,Eligible,Eligible,Eligible
5,Arjun,M,AI,24,76,69,80,82,225,75.000000,Pass,Good,,Eligible,Eligible,Eligible
6,Divya,F,AI,22,92,87,95,98,274,91.333333,Pass,Excellent,,Eligible,Eligible,Eligible
7,Rohit,M,Python,26,81,79,73,88,233,77.666667,Pass,Good,,Eligible,Eligible,Eligible
8,Meena,F,AI,23,88,93,89,91,270,90.000000,Pass,Excellent,,Eligible,Eligible,Eligible
9,Varun,M,Data Science,25,65,72,68,75,205,68.333333,Pass,Average,,Eligible,Eligible,Eligible

In [72]:
df.drop("Attendance_Status", axis=1, inplace=True)

In [73]:
df

,Name,Gender,Department,Age,Python,SQL,Pandas,Attendance,Total,Average,Result,Performance,Attendance_status,Not Eligible,Attendance_stattus
0,Anu,F,Data Science,22,85,78,90,92,253,84.333333,Pass,Good,,Eligible,Eligible
1,Ravi,M,Data Science,24,72,88,75,85,235,78.333333,Pass,Good,,Eligible,Eligible
2,Priya,F,Python,21,95,82,91,96,268,89.333333,Pass,Excellent,,Eligible,Eligible
3,Kiran,M,Python,23,68,74,70,78,212,70.666667,Pass,Average,,Eligible,Eligible
4,Sneha,F,Data Science,25,89,91,86,94,266,88.666667,Pass,Excellent,,Eligible,Eligible
5,Arjun,M,AI,24,76,69,80,82,225,75.000000,Pass,Good,,Eligible,Eligible
6,Divya,F,AI,22,92,87,95,98,274,91.333333,Pass,Excellent,,Eligible,Eligible
7,Rohit,M,Python,26,81,79,73,88,233,77.666667,Pass,Good,,Eligible,Eligible
8,Meena,F,AI,23,88,93,89,91,270,90.000000,Pass,Excellent,,Eligible,Eligible
9,Varun,M,Data Science,25,65,72,68,75,205,68.333333,Pass,Average,,Eligible,Eligible

# 🔵 Level 4 – Sorting

Sort students based on Average in descending order.

Find the top 3 students based on average marks.

Sort students based on attendance from highest to lowest.

Sort the DataFrame first by Department and then by Average.

In [75]:
df.sort_values("Average",ascending = False)

,Name,Gender,Department,Age,Python,SQL,Pandas,Attendance,Total,Average,Result,Performance,Attendance_status,Not Eligible,Attendance_stattus,Attendance_Status
6,Divya,F,AI,22,92,87,95,98,274,91.333333,Pass,Excellent,,Eligible,Eligible,Eligible
8,Meena,F,AI,23,88,93,89,91,270,90.000000,Pass,Excellent,,Eligible,Eligible,Eligible
2,Priya,F,Python,21,95,82,91,96,268,89.333333,Pass,Excellent,,Eligible,Eligible,Eligible
4,Sneha,F,Data Science,25,89,91,86,94,266,88.666667,Pass,Excellent,,Eligible,Eligible,Eligible
0,Anu,F,Data Science,22,85,78,90,92,253,84.333333,Pass,Good,,Eligible,Eligible,Eligible
1,Ravi,M,Data Science,24,72,88,75,85,235,78.333333,Pass,Good,,Eligible,Eligible,Eligible
7,Rohit,M,Python,26,81,79,73,88,233,77.666667,Pass,Good,,Eligible,Eligible,Eligible
5,Arjun,M,AI,24,76,69,80,82,225,75.000000,Pass,Good,,Eligible,Eligible,Eligible
3,Kiran,M,Python,23,68,74,70,78,212,70.666667,Pass,Average,,Eligible,Eligible,Eligible
9,Varun,M,Data Science,25,65,72,68,75,205,68.333333,Pass,Average,,Eligible,Eligible,Eligible

In [76]:
df.sort_values("Average",ascending = False).head(3)

,Name,Gender,Department,Age,Python,SQL,Pandas,Attendance,Total,Average,Result,Performance,Attendance_status,Not Eligible,Attendance_stattus,Attendance_Status
6,Divya,F,AI,22,92,87,95,98,274,91.333333,Pass,Excellent,,Eligible,Eligible,Eligible
8,Meena,F,AI,23,88,93,89,91,270,90.000000,Pass,Excellent,,Eligible,Eligible,Eligible
2,Priya,F,Python,21,95,82,91,96,268,89.333333,Pass,Excellent,,Eligible,Eligible,Eligible

In [77]:
df.sort_values("Attendance",ascending = False)

,Name,Gender,Department,Age,Python,SQL,Pandas,Attendance,Total,Average,Result,Performance,Attendance_status,Not Eligible,Attendance_stattus,Attendance_Status
6,Divya,F,AI,22,92,87,95,98,274,91.333333,Pass,Excellent,,Eligible,Eligible,Eligible
2,Priya,F,Python,21,95,82,91,96,268,89.333333,Pass,Excellent,,Eligible,Eligible,Eligible
4,Sneha,F,Data Science,25,89,91,86,94,266,88.666667,Pass,Excellent,,Eligible,Eligible,Eligible
0,Anu,F,Data Science,22,85,78,90,92,253,84.333333,Pass,Good,,Eligible,Eligible,Eligible
8,Meena,F,AI,23,88,93,89,91,270,90.000000,Pass,Excellent,,Eligible,Eligible,Eligible
7,Rohit,M,Python,26,81,79,73,88,233,77.666667,Pass,Good,,Eligible,Eligible,Eligible
1,Ravi,M,Data Science,24,72,88,75,85,235,78.333333,Pass,Good,,Eligible,Eligible,Eligible
5,Arjun,M,AI,24,76,69,80,82,225,75.000000,Pass,Good,,Eligible,Eligible,Eligible
3,Kiran,M,Python,23,68,74,70,78,212,70.666667,Pass,Average,,Eligible,Eligible,Eligible
9,Varun,M,Data Science,25,65,72,68,75,205,68.333333,Pass,Average,,Eligible,Eligible,Eligible

In [78]:
df.sort_values(["Department","Average"],ascending = [True,False])

,Name,Gender,Department,Age,Python,SQL,Pandas,Attendance,Total,Average,Result,Performance,Attendance_status,Not Eligible,Attendance_stattus,Attendance_Status
6,Divya,F,AI,22,92,87,95,98,274,91.333333,Pass,Excellent,,Eligible,Eligible,Eligible
8,Meena,F,AI,23,88,93,89,91,270,90.000000,Pass,Excellent,,Eligible,Eligible,Eligible
5,Arjun,M,AI,24,76,69,80,82,225,75.000000,Pass,Good,,Eligible,Eligible,Eligible
4,Sneha,F,Data Science,25,89,91,86,94,266,88.666667,Pass,Excellent,,Eligible,Eligible,Eligible
0,Anu,F,Data Science,22,85,78,90,92,253,84.333333,Pass,Good,,Eligible,Eligible,Eligible
1,Ravi,M,Data Science,24,72,88,75,85,235,78.333333,Pass,Good,,Eligible,Eligible,Eligible
9,Varun,M,Data Science,25,65,72,68,75,205,68.333333,Pass,Average,,Eligible,Eligible,Eligible
2,Priya,F,Python,21,95,82,91,96,268,89.333333,Pass,Excellent,,Eligible,Eligible,Eligible
7,Rohit,M,Python,26,81,79,73,88,233,77.666667,Pass,Good,,Eligible,Eligible,Eligible
3,Kiran,M,Python,23,68,74,70,78,212,70.666667,Pass,Average,,Eligible,Eligible,Eligible

# 🟣 Level 5 – GroupBy

Find the average Python score of each department.

Find the average SQL score of each department.

Find the average Pandas score of each department.

Find the average attendance of each department.

Find the number of students in each department.

Find the highest Python score in each department.

Find the lowest SQL score in each department.

Which department has the highest average Pandas score?

Which department has the highest average attendance?

In [82]:
df.groupby('Department')[["Python"]].mean()

                 Python
Department
AI            85.333333
Data Science  77.750000
Python        81.333333

In [83]:
df.groupby('Department')[["SQL"]].mean()

                    SQL
Department
AI            83.000000
Data Science  82.250000
Python        78.333333

In [84]:
df.groupby('Department')[["Pandas"]].mean()

              Pandas
Department
AI             88.00
Data Science   79.75
Python         78.00

In [86]:
df.groupby('Department')[["Attendance"]].mean()

              Attendance
Department
AI             90.333333
Data Science   86.500000
Python         87.333333

In [91]:
df.groupby('Department').size()

Department
AI              3
Data Science    4
Python          3
dtype: int64

In [95]:
df.groupby("Department")[["Python"]].max()

              Python
Department
AI                92
Data Science      89
Python            95

In [96]:
df.groupby("Department")[["SQL"]].min()

              SQL
Department
AI             69
Data Science   72
Python         74

In [94]:
df.groupby("Department")["Pandas"].mean().idxmax()

'AI'

# 🔴 Level 6 – Real-Time Challenge Questions

Find the top-performing student in each department.
    
Find the department with the highest average overall score.
    
Find students who have:
    
Python > 80
    
SQL > 80

Pandas > 80
    
Attendance > 85

Find students who performed well academically but have attendance below 80%.
    
Find students whose Pandas score is higher than their Python score.
    
Find students whose SQL score is higher than both Python and Pandas.

In [98]:
df.loc[df.groupby("Department")["Average"].idxmax()]

,Name,Gender,Department,Age,Python,SQL,Pandas,Attendance,Total,Average,Result,Performance,Attendance_status,Not Eligible,Attendance_stattus,Attendance_Status
6,Divya,F,AI,22,92,87,95,98,274,91.333333,Pass,Excellent,,Eligible,Eligible,Eligible
4,Sneha,F,Data Science,25,89,91,86,94,266,88.666667,Pass,Excellent,,Eligible,Eligible,Eligible
2,Priya,F,Python,21,95,82,91,96,268,89.333333,Pass,Excellent,,Eligible,Eligible,Eligible

In [99]:
df.groupby("Department")["Average"].mean().idxmax()

'AI'

In [100]:
df[(df["Python"] > 80) &(df["SQL"] > 80) &(df["Pandas"] > 80) &(df["Attendance"] > 85)]

,Name,Gender,Department,Age,Python,SQL,Pandas,Attendance,Total,Average,Result,Performance,Attendance_status,Not Eligible,Attendance_stattus,Attendance_Status
2,Priya,F,Python,21,95,82,91,96,268,89.333333,Pass,Excellent,,Eligible,Eligible,Eligible
4,Sneha,F,Data Science,25,89,91,86,94,266,88.666667,Pass,Excellent,,Eligible,Eligible,Eligible
6,Divya,F,AI,22,92,87,95,98,274,91.333333,Pass,Excellent,,Eligible,Eligible,Eligible
8,Meena,F,AI,23,88,93,89,91,270,90.000000,Pass,Excellent,,Eligible,Eligible,Eligible

In [101]:
df[(df["Average"] >= 75) & (df["Attendance"] < 80)]

Empty DataFrame
Columns: [Name, Gender, Department, Age, Python, SQL, Pandas, Attendance, Total, Average, Result, Performance, Attendance_status,  Not Eligible,  Attendance_stattus, Attendance_Status]
Index: []

In [102]:
df[df["Pandas"] > df["Python"]]

,Name,Gender,Department,Age,Python,SQL,Pandas,Attendance,Total,Average,Result,Performance,Attendance_status,Not Eligible,Attendance_stattus,Attendance_Status
0,Anu,F,Data Science,22,85,78,90,92,253,84.333333,Pass,Good,,Eligible,Eligible,Eligible
1,Ravi,M,Data Science,24,72,88,75,85,235,78.333333,Pass,Good,,Eligible,Eligible,Eligible
3,Kiran,M,Python,23,68,74,70,78,212,70.666667,Pass,Average,,Eligible,Eligible,Eligible
5,Arjun,M,AI,24,76,69,80,82,225,75.000000,Pass,Good,,Eligible,Eligible,Eligible
6,Divya,F,AI,22,92,87,95,98,274,91.333333,Pass,Excellent,,Eligible,Eligible,Eligible
8,Meena,F,AI,23,88,93,89,91,270,90.000000,Pass,Excellent,,Eligible,Eligible,Eligible
9,Varun,M,Data Science,25,65,72,68,75,205,68.333333,Pass,Average,,Eligible,Eligible,Eligible

In [103]:
df[
    (df["SQL"] > df["Python"]) &
    (df["SQL"] > df["Pandas"])
]

,Name,Gender,Department,Age,Python,SQL,Pandas,Attendance,Total,Average,Result,Performance,Attendance_status,Not Eligible,Attendance_stattus,Attendance_Status
1,Ravi,M,Data Science,24,72,88,75,85,235,78.333333,Pass,Good,,Eligible,Eligible,Eligible
3,Kiran,M,Python,23,68,74,70,78,212,70.666667,Pass,Average,,Eligible,Eligible,Eligible
4,Sneha,F,Data Science,25,89,91,86,94,266,88.666667,Pass,Excellent,,Eligible,Eligible,Eligible
8,Meena,F,AI,23,88,93,89,91,270,90.000000,Pass,Excellent,,Eligible,Eligible,Eligible
9,Varun,M,Data Science,25,65,72,68,75,205,68.333333,Pass,Average,,Eligible,Eligible,Eligible

In [104]:
percentage = (df["Attendance"].ge(85).mean()) * 100

print(percentage)

70.0

In [105]:
df.groupby("Gender")["Average"].mean()

Gender
F    88.733333
M    74.000000
Name: Average, dtype: float64

In [106]:
df.groupby("Gender")["Python"].mean().idxmax()

'F'

In [107]:
df[df["Attendance"] < 90].sort_values(
    "Total", ascending=False
).head(1)

,Name,Gender,Department,Age,Python,SQL,Pandas,Attendance,Total,Average,Result,Performance,Attendance_status,Not Eligible,Attendance_stattus,Attendance_Status
1,Ravi,M,Data Science,24,72,88,75,85,235,78.333333,Pass,Good,,Eligible,Eligible,Eligible