# Task 1: Understand the Dataset
Create a DataFrame using:
- import pandas as pd

In [2]:
import pandas as pd

data = {
    "Name": ["Asha", "Rahul", "Priya", "Kiran", "Arjun"],
    "Age": [21, 24, 22, 25, 23],
    "City": ["Hyderabad", "Delhi", "Mumbai", "Hyderabad", "Chennai"],
    "Salary": [25000, 32000, 28000, 40000, 30000]
}

df = pd.DataFrame(data)
df

    Name  Age       City  Salary
0   Asha   21  Hyderabad   25000
1  Rahul   24      Delhi   32000
2  Priya   22     Mumbai   28000
3  Kiran   25  Hyderabad   40000
4  Arjun   23    Chennai   30000

# Display the first 5 rows.

In [4]:
df.head()

    Name  Age       City  Salary
0   Asha   21  Hyderabad   25000
1  Rahul   24      Delhi   32000
2  Priya   22     Mumbai   28000
3  Kiran   25  Hyderabad   40000
4  Arjun   23    Chennai   30000

# Display the last 3 rows.

In [6]:
df.tail(3)

    Name  Age       City  Salary
2  Priya   22     Mumbai   28000
3  Kiran   25  Hyderabad   40000
4  Arjun   23    Chennai   30000

# Find the number of rows and columns.

In [10]:
df.shape

(5, 4)

# Display all column names

In [11]:
df.columns

Index(['Name', 'Age', 'City', 'Salary'], dtype='object')

# Display basic information about the DataFrame.

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
 3   Salary  5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 288.0+ bytes

# Check the data types of each column.

In [15]:
df.dtypes

Name      object
Age        int64
City      object
Salary     int64
dtype: object

# Task 2: Basic Data Inspection

Using the same DataFrame:

Find the total number of records.

Find the average salary.

Find the minimum salary.

Find the maximum salary.

Find the average age.

Find the oldest person.

Find the youngest person.

***Concepts: shape, mean(), min(), max()***

In [16]:
df.shape[0]

5

In [18]:
print(df["Salary"].mean())

31000.0

In [19]:
print(df["Salary"].min())

25000

In [20]:
print(df["Salary"].max())

40000

In [21]:
print(df["Age"].min())

21

In [22]:
print(df["Age"].max())

25

In [27]:
print(df["Age"].mean())

23.0

# Task 3: Selecting Columns

From the DataFrame:

Display only Name.

Display only Salary.

Display Name and City.

Display Name, Age, and Salary.

**Concept: Column selection.**

In [28]:
df["Name"]

0     Asha
1    Rahul
2    Priya
3    Kiran
4    Arjun
Name: Name, dtype: object

In [29]:
df["Salary"]

0    25000
1    32000
2    28000
3    40000
4    30000
Name: Salary, dtype: int64

In [31]:
df[["Name","City"]]

    Name       City
0   Asha  Hyderabad
1  Rahul      Delhi
2  Priya     Mumbai
3  Kiran  Hyderabad
4  Arjun    Chennai

In [32]:
df[["Name","Age","Salary"]]

    Name  Age  Salary
0   Asha   21   25000
1  Rahul   24   32000
2  Priya   22   28000
3  Kiran   25   40000
4  Arjun   23   30000

# Task 4: Filtering Data

Find:

People whose salary is greater than ₹30,000.

People whose age is greater than 22.

People from Hyderabad.

People whose salary is less than ₹30,000.

People whose age is between 22 and 24.

**Concepts: Boolean filtering, conditions, &, |**

In [36]:
df[df["Salary"]>30000]

    Name  Age       City  Salary
1  Rahul   24      Delhi   32000
3  Kiran   25  Hyderabad   40000

In [37]:
df[df["Age"]>22]

    Name  Age       City  Salary
1  Rahul   24      Delhi   32000
3  Kiran   25  Hyderabad   40000
4  Arjun   23    Chennai   30000

In [41]:
df[df["City"]=="Hyderabad"][["Name","City"]]

    Name       City
0   Asha  Hyderabad
3  Kiran  Hyderabad

In [42]:
df[df["Salary"]<30000]

    Name  Age       City  Salary
0   Asha   21  Hyderabad   25000
2  Priya   22     Mumbai   28000

In [47]:
df[(df["Age"]>22) & (df ["Age"]<24)]

    Name  Age     City  Salary
4  Arjun   23  Chennai   30000

# Task 5: Sorting

Sort employees by salary from lowest to highest
    
Sort employees by salary from highest to lowest.
    
Sort employees by age.
    
Find the employee with the highest salary.
    
**Concept: sort_values()**

In [48]:
df.sort_values(by = "Salary")

    Name  Age       City  Salary
0   Asha   21  Hyderabad   25000
2  Priya   22     Mumbai   28000
4  Arjun   23    Chennai   30000
1  Rahul   24      Delhi   32000
3  Kiran   25  Hyderabad   40000

In [57]:
df.sort_values(by=["Salary"], ascending= False)

    Name  Age       City  Salary
3  Kiran   25  Hyderabad   40000
1  Rahul   24      Delhi   32000
4  Arjun   23    Chennai   30000
2  Priya   22     Mumbai   28000
0   Asha   21  Hyderabad   25000

In [56]:
df.sort_values(by = "Age")

    Name  Age       City  Salary
0   Asha   21  Hyderabad   25000
2  Priya   22     Mumbai   28000
4  Arjun   23    Chennai   30000
1  Rahul   24      Delhi   32000
3  Kiran   25  Hyderabad   40000

In [69]:
df.loc[[df["Salary"].idxmax()],["Name","Salary"]]

    Name  Salary
3  Kiran   40000

In [71]:
df.sort_values(by = 'Salary',ascending = False)[['Name','Salary']].head(1)

    Name  Salary
3  Kiran   40000

# Read iris dataset 👍

# Basic understanding

Display the first 5 rows.
    
Display the last 5 rows.
    
Find the number of rows and columns.
    
Display the column names.
    
Check the data types of all columns.
    
Use info() to understand the dataset.
    
Use describe() to get statistical information.

In [72]:
df.head(5)

    Name  Age       City  Salary
0   Asha   21  Hyderabad   25000
1  Rahul   24      Delhi   32000
2  Priya   22     Mumbai   28000
3  Kiran   25  Hyderabad   40000
4  Arjun   23    Chennai   30000

In [78]:
df.tail(5)

    Name  Age       City  Salary
0   Asha   21  Hyderabad   25000
1  Rahul   24      Delhi   32000
2  Priya   22     Mumbai   28000
3  Kiran   25  Hyderabad   40000
4  Arjun   23    Chennai   30000

In [80]:
df.shape

(5, 4)

In [83]:
df.columns

Index(['Name', 'Age', 'City', 'Salary'], dtype='object')

In [84]:
df.dtypes

Name      object
Age        int64
City      object
Salary     int64
dtype: object

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
 3   Salary  5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 288.0+ bytes

In [86]:
df.describe()

             Age        Salary
count   5.000000      5.000000
mean   23.000000  31000.000000
std     1.581139   5656.854249
min    21.000000  25000.000000
25%    22.000000  28000.000000
50%    23.000000  30000.000000
75%    24.000000  32000.000000
max    25.000000  40000.000000

# Data analysis

Find the average sepal_length.

Find the maximum petal_length.

Find the minimum petal_width.

Find the number of flowers in each species.

Display only the setosa flowers.

Find flowers where petal_length > 5.

Sort the dataset according to petal_length.

Find the average petal_length for each species.

In [1]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\thars\appdata\local\programs\python\python310\lib\site-packages (1.7.2)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: numpy>=1.22.0 in c:\users\thars\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (2.2.6)
Requirement already satisfied: scipy>=1.8.0 in c:\users\thars\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\thars\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\thars\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (3.6.0)

In [2]:
from sklearn.datasets import load_iris

In [5]:
iris = load_iris()
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [7]:
import pandas as pd

df = pd.DataFrame(iris.data, columns=iris.feature_names)
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [11]:
df['species'] = iris.target_names[iris.target]
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

In [16]:
df.columns = ['sepal_length','sepal_width','petal_length','petal_width','species']
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [17]:
df["sepal_length"].mean()

np.float64(5.843333333333334)

In [18]:
df["petal_length"].max()

np.float64(6.9)

In [19]:
df["petal_width"].max()

np.float64(2.5)

In [23]:
df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [20]:
df[df["species"]=="setosa"]["species"]

0     setosa
1     setosa
2     setosa
3     setosa
4     setosa
5     setosa
6     setosa
7     setosa
8     setosa
9     setosa
10    setosa
11    setosa
12    setosa
13    setosa
14    setosa
15    setosa
16    setosa
17    setosa
18    setosa
19    setosa
20    setosa
21    setosa
22    setosa
23    setosa
24    setosa
25    setosa
26    setosa
27    setosa
28    setosa
29    setosa
30    setosa
31    setosa
32    setosa
33    setosa
34    setosa
35    setosa
36    setosa
37    setosa
38    setosa
39    setosa
40    setosa
41    setosa
42    setosa
43    setosa
44    setosa
45    setosa
46    setosa
47    setosa
48    setosa
49    setosa
Name: species, dtype: object

In [21]:
df[df["petal_length"]>5]

     sepal_length  sepal_width  petal_length  petal_width     species
83            6.0          2.7           5.1          1.6  versicolor
100           6.3          3.3           6.0          2.5   virginica
101           5.8          2.7           5.1          1.9   virginica
102           7.1          3.0           5.9          2.1   virginica
103           6.3          2.9           5.6          1.8   virginica
104           6.5          3.0           5.8          2.2   virginica
105           7.6          3.0           6.6          2.1   virginica
107           7.3          2.9           6.3          1.8   virginica
108           6.7          2.5           5.8          1.8   virginica
109           7.2          3.6           6.1          2.5   virginica
110           6.5          3.2           5.1          2.0   virginica
111           6.4          2.7           5.3          1.9   virginica
112           6.8          3.0           5.5          2.1   virginica
114           5.8          2.8           5.1          2.4   virginica
115           6.4          3.2           5.3          2.3   virginica
116           6.5          3.0           5.5          1.8   virginica
117           7.7          3.8           6.7          2.2   virginica
118           7.7          2.6           6.9          2.3   virginica
120           6.9          3.2           5.7          2.3   virginica
122           7.7          2.8           6.7          2.0   virginica
124           6.7          3.3           5.7          2.1   virginica
125           7.2          3.2           6.0          1.8   virginica
128           6.4          2.8           5.6          2.1   virginica
129           7.2          3.0           5.8          1.6   virginica
130           7.4          2.8           6.1          1.9   virginica
131           7.9          3.8           6.4          2.0   virginica
132           6.4          2.8           5.6          2.2   virginica
133           6.3          2.8           5.1          1.5   virginica
134           6.1          2.6           5.6          1.4   virginica
135           7.7          3.0           6.1          2.3   virginica
136           6.3          3.4           5.6          2.4   virginica
137           6.4          3.1           5.5          1.8   virginica
139           6.9          3.1           5.4          2.1   virginica
140           6.7          3.1           5.6          2.4   virginica
141           6.9          3.1           5.1          2.3   virginica
142           5.8          2.7           5.1          1.9   virginica
143           6.8          3.2           5.9          2.3   virginica
144           6.7          3.3           5.7          2.5   virginica
145           6.7          3.0           5.2          2.3   virginica
147           6.5          3.0           5.2          2.0   virginica
148           6.2          3.4           5.4          2.3   virginica
149           5.9          3.0           5.1          1.8   virginica

In [24]:
df.sort_values(by = "petal_length")

     sepal_length  sepal_width  petal_length  petal_width    species
22            4.6          3.6           1.0          0.2     setosa
13            4.3          3.0           1.1          0.1     setosa
14            5.8          4.0           1.2          0.2     setosa
35            5.0          3.2           1.2          0.2     setosa
16            5.4          3.9           1.3          0.4     setosa
..            ...          ...           ...          ...        ...
131           7.9          3.8           6.4          2.0  virginica
105           7.6          3.0           6.6          2.1  virginica
117           7.7          3.8           6.7          2.2  virginica
122           7.7          2.8           6.7          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica

[150 rows x 5 columns]

In [27]:
print(df.groupby('species')["petal_length"].mean())

species
setosa        1.462
versicolor    4.260
virginica     5.552
Name: petal_length, dtype: float64